"""init

Revision ID: 1fc71d78241b
Revises: 
Create Date: 2026-04-20 17:39:34.817990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1fc71d78241b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('badges',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('main_color', sa.String(length=20), server_default='#3b82f6', nullable=False),
    sa.Column('secondary_color', sa.String(length=20), server_default='#1e40af', nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gem_categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gem_tags',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.Enum('SUPER_ADMIN', 'CONTENT_ADMIN', 'CONTENT_EDITOR', 'CONTENT_VIEWER', 'LEARNER', name='role_name_enum', native_enum=False), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('area_id', sa.CHAR(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='user_status_enum', native_enum=False), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('area_id', sa.CHAR(length=36), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='course_status_enum', native_enum=False), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('access_type', sa.Enum('free', 'restricted', name='course_access_type_enum', native_enum=False), server_default=sa.text("'free'"), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_posts',
    sa.Column('area_id', sa.CHAR(length=36), nullable=True),
    sa.Column('author_user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('multimedia_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='forum_post_status_enum', native_enum=False), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forum_posts_area_status', 'forum_posts', ['area_id', 'status'], unique=False)
    op.create_index('idx_forum_posts_author', 'forum_posts', ['author_user_id'], unique=False)
    op.create_table('gems',
    sa.Column('category_id', sa.CHAR(length=36), nullable=True),
    sa.Column('area_id', sa.CHAR(length=36), nullable=True),
    sa.Column('created_by_user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('gemini_url', sa.Text(), nullable=True),
    sa.Column('conversation_starters', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'SHARED', 'PUBLIC', name='gem_visibility_enum', native_enum=False), server_default=sa.text("'public'"), nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='gem_status_enum', native_enum=False), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('usage_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['gem_categories.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gems_area_status', 'gems', ['area_id', 'status'], unique=False)
    op.create_index('idx_gems_category', 'gems', ['category_id'], unique=False)
    op.create_index('idx_gems_created_by', 'gems', ['created_by_user_id'], unique=False)
    op.create_index('idx_gems_featured', 'gems', ['is_featured', 'status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_activity_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('badge_id', sa.CHAR(length=36), nullable=False),
    sa.Column('awarded_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badges_user_badge')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('role_id', sa.CHAR(length=36), nullable=False),
    sa.Column('assigned_by_user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('course_assignments',
    sa.Column('course_id', sa.CHAR(length=36), nullable=False),
    sa.Column('assigned_by_user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('assigned_to_user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('due_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assigned_to_user_id', 'course_id', name='uq_course_assignments_user_course')
    )
    op.create_index('idx_course_assignments_assigned_by', 'course_assignments', ['assigned_by_user_id'], unique=False)
    op.create_index('idx_course_assignments_due_date', 'course_assignments', ['due_date'], unique=False)
    op.create_table('course_badges',
    sa.Column('course_id', sa.CHAR(length=36), nullable=False),
    sa.Column('badge_id', sa.CHAR(length=36), nullable=False),
    sa.Column('progress_percentage', sa.DECIMAL(precision=5, scale=2), server_default=sa.text('100.00'), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'badge_id', name='uq_course_badges_course_badge')
    )
    op.create_table('course_certifications',
    sa.Column('course_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id')
    )
    op.create_table('course_gems',
    sa.Column('course_id', sa.CHAR(length=36), nullable=False),
    sa.Column('gem_id', sa.CHAR(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gem_id'], ['gems.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'gem_id', name='uq_course_gems_course_gem')
    )
    op.create_table('course_modules',
    sa.Column('course_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'sort_order', name='uq_course_modules_course_sort')
    )
    op.create_table('enrollments',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('course_id', sa.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'dropped', name='enrollment_status_enum', native_enum=False), server_default=sa.text("'active'"), nullable=False),
    sa.Column('progress_percent', sa.DECIMAL(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_activity_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_enrollments_user_course')
    )
    op.create_table('forum_comments',
    sa.Column('post_id', sa.CHAR(length=36), nullable=False),
    sa.Column('author_user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('parent_comment_id', sa.CHAR(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['forum_comments.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gem_area_links',
    sa.Column('gem_id', sa.CHAR(length=36), nullable=False),
    sa.Column('area_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gem_id'], ['gems.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gem_id', 'area_id')
    )
    op.create_table('gem_tag_links',
    sa.Column('gem_id', sa.CHAR(length=36), nullable=False),
    sa.Column('tag_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['gem_id'], ['gems.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['gem_tags.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gem_id', 'tag_id')
    )
    op.create_table('user_course_grants',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('course_id', sa.CHAR(length=36), nullable=False),
    sa.Column('granted_by_user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_user_course_grants_user_course')
    )
    op.create_index('idx_user_course_grants_user', 'user_course_grants', ['user_id'], unique=False)
    op.create_table('user_gem_collection',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('gem_id', sa.CHAR(length=36), nullable=False),
    sa.Column('saved_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['gem_id'], ['gems.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gem_id', name='uq_user_gem_collection_user_gem')
    )
    op.create_table('lessons',
    sa.Column('module_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'sort_order', name='uq_lessons_module_sort')
    )
    op.create_table('user_certifications',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('course_certification_id', sa.CHAR(length=36), nullable=False),
    sa.Column('enrollment_id', sa.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'ISSUED', 'REJECTED', name='certification_request_status_enum', native_enum=False), server_default=sa.text("'requested'"), nullable=False),
    sa.Column('requested_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('approved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('issued_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('rejected_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('expiration_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('certificate_code', sa.String(length=100), nullable=True),
    sa.Column('certificate_url', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['course_certification_id'], ['course_certifications.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_code'),
    sa.UniqueConstraint('user_id', 'course_certification_id', name='uq_user_certifications_user_cert')
    )
    op.create_index('idx_user_certifications_status', 'user_certifications', ['status'], unique=False)
    op.create_index('idx_user_certifications_user', 'user_certifications', ['user_id'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('area_id', sa.CHAR(length=36), nullable=True),
    sa.Column('course_id', sa.CHAR(length=36), nullable=True),
    sa.Column('lesson_id', sa.CHAR(length=36), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_events_area', 'analytics_events', ['area_id'], unique=False)
    op.create_index('idx_analytics_events_course', 'analytics_events', ['course_id'], unique=False)
    op.create_index('idx_analytics_events_lesson', 'analytics_events', ['lesson_id'], unique=False)
    op.create_index('idx_analytics_events_name_time', 'analytics_events', ['event_name', 'event_time'], unique=False)
    op.create_index('idx_analytics_events_user', 'analytics_events', ['user_id'], unique=False)
    op.create_table('lesson_gems',
    sa.Column('lesson_id', sa.CHAR(length=36), nullable=False),
    sa.Column('gem_id', sa.CHAR(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['gem_id'], ['gems.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'gem_id', name='uq_lesson_gems_lesson_gem')
    )
    op.create_table('lesson_progress',
    sa.Column('enrollment_id', sa.CHAR(length=36), nullable=False),
    sa.Column('lesson_id', sa.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='lesson_progress_status_enum', native_enum=False), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('progress_percent', sa.DECIMAL(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_activity_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'lesson_id', name='uq_lesson_progress_enrollment_lesson')
    )
    op.create_table('lesson_resources',
    sa.Column('lesson_id', sa.CHAR(length=36), nullable=False),
    sa.Column('resource_type', sa.Enum('VIDEO', 'PDF', 'PODCAST', 'SLIDE', name='lesson_resource_type_enum', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('external_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizzes',
    sa.Column('lesson_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('passing_score', sa.DECIMAL(precision=5, scale=2), server_default=sa.text('70.00'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id')
    )
    op.create_table('quiz_attempts',
    sa.Column('quiz_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('enrollment_id', sa.CHAR(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'TIMED_OUT', name='quiz_attempt_status_enum', native_enum=False), server_default=sa.text("'in_progress'"), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'user_id', 'attempt_number', name='uq_quiz_attempts_quiz_user_attempt')
    )
    op.create_index('idx_quiz_attempts_enrollment', 'quiz_attempts', ['enrollment_id'], unique=False)
    op.create_index('idx_quiz_attempts_user_quiz', 'quiz_attempts', ['user_id', 'quiz_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('quiz_id', sa.CHAR(length=36), nullable=False),
    sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'TRUE_FALSE', 'SHORT_ANSWER', 'ORDERING', 'MATCHING', name='question_type_enum', native_enum=False), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('points', sa.DECIMAL(precision=5, scale=2), server_default=sa.text('1.00'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'sort_order', name='uq_quiz_questions_quiz_sort')
    )
    op.create_table('quiz_question_options',
    sa.Column('question_id', sa.CHAR(length=36), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('match_target', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'sort_order', name='uq_quiz_question_options_question_sort')
    )
    op.create_table('quiz_attempt_responses',
    sa.Column('attempt_id', sa.CHAR(length=36), nullable=False),
    sa.Column('question_id', sa.CHAR(length=36), nullable=False),
    sa.Column('selected_option_id', sa.CHAR(length=36), nullable=True),
    sa.Column('text_response', sa.Text(), nullable=True),
    sa.Column('ordering_response', sa.JSON(), nullable=True),
    sa.Column('matching_response', sa.JSON(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_earned', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['quiz_question_options.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_quiz_attempt_responses_attempt_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_attempt_responses')
    op.drop_table('quiz_question_options')
    op.drop_table('quiz_questions')
    op.drop_index('idx_quiz_attempts_user_quiz', table_name='quiz_attempts')
    op.drop_index('idx_quiz_attempts_enrollment', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_table('quizzes')
    op.drop_table('lesson_resources')
    op.drop_table('lesson_progress')
    op.drop_table('lesson_gems')
    op.drop_index('idx_analytics_events_user', table_name='analytics_events')
    op.drop_index('idx_analytics_events_name_time', table_name='analytics_events')
    op.drop_index('idx_analytics_events_lesson', table_name='analytics_events')
    op.drop_index('idx_analytics_events_course', table_name='analytics_events')
    op.drop_index('idx_analytics_events_area', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index('idx_user_certifications_user', table_name='user_certifications')
    op.drop_index('idx_user_certifications_status', table_name='user_certifications')
    op.drop_table('user_certifications')
    op.drop_table('lessons')
    op.drop_table('user_gem_collection')
    op.drop_index('idx_user_course_grants_user', table_name='user_course_grants')
    op.drop_table('user_course_grants')
    op.drop_table('gem_tag_links')
    op.drop_table('gem_area_links')
    op.drop_table('forum_comments')
    op.drop_table('enrollments')
    op.drop_table('course_modules')
    op.drop_table('course_gems')
    op.drop_table('course_certifications')
    op.drop_table('course_badges')
    op.drop_index('idx_course_assignments_due_date', table_name='course_assignments')
    op.drop_index('idx_course_assignments_assigned_by', table_name='course_assignments')
    op.drop_table('course_assignments')
    op.drop_table('user_roles')
    op.drop_table('user_badges')
    op.drop_index('idx_sessions_user_id', table_name='sessions')
    op.drop_index('idx_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_gems_featured', table_name='gems')
    op.drop_index('idx_gems_created_by', table_name='gems')
    op.drop_index('idx_gems_category', table_name='gems')
    op.drop_index('idx_gems_area_status', table_name='gems')
    op.drop_table('gems')
    op.drop_index('idx_forum_posts_author', table_name='forum_posts')
    op.drop_index('idx_forum_posts_area_status', table_name='forum_posts')
    op.drop_table('forum_posts')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('gem_tags')
    op.drop_table('gem_categories')
    op.drop_table('badges')
    op.drop_table('areas')
    # ### end Alembic commands ###